### ISSUE TITLE
Line up and down

### ISSUE THREAD

**Issue by Qaezel** [hpoul/dart-editor-emacs-keybindings#3]
On OSX, I'm still unable to move the line up and down using ctrl+p and ctrl+n. Any tips?

**Comment by hpoul** [comment]
this is weird, which dart editor version are you using?
are other shortcuts working for you? e.g. alt+f / alt+b for word forward/backward?

**Comment by Qaezel** [comment]
Dart Editor version 1.7.2.release (STABLE); the alt+f, alt+b work correctly. ctrl+a and ctrl+e for beginning of the line and end of the line work as well. I've also modified some other things, like having ctrl+B to delete the previous word.

**Comment by hpoul** [comment]
i'm also on a mac (10.9.5) and also had the 1.7.2 dev channel build .. and everything works.. are ctrl+p/n work in other apps, have you ever tried a vanilla eclipse installation with eclipse bindings, if those shortcuts work there?

would you mind sharing your additional shortcuts? :-)

**Comment by Qaezel** [comment]
I have a Japanese keyboard: <a href='https://www.google.com/search?q=mac+keyboard&espv=2&biw=1098&bih=733&tbm=isch&tbo=u&source=univ&sa=X&ei=j4NMVL7LJ5P38QWVyYGgDg&ved=0CDEQsAQ#tbm=isch&q=mac+keyboard+japanese&facrc=_&imgdii=_&imgrc=khGqmQdM57XZcM%253A%3BEp7v40k0SMf9jM%3Bhttp%253A%252F%252Fmedia.tumblr.com%252F8a802af0eab218f3d3893d386e6f9580%252Ftumblr_inline_mmmtmmv6JT1qz4rgp.jpg%3Bhttp%253A%252F%252Fadamukun.tumblr.com%252Fpost%252F50159898648%252Fsetting-up-a-japanese-mac-wireless-keyboard-on-windows%3B500%3B280'> Picture </a> My Control key is right next to the 'A' key, which makes using CTRL+ anything really easy. I also have <a href='https://pqrs.org/osx/karabiner/'>Karabiner</a> installed. I swapped the single quote key and kana key; and the @ key with the = key. I will have to debug this when I have time. I'll let you know how it goes. Thanks
